parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2022
  sourceType: module
  project: ['./tsconfig.json', './tsconfig.spec.json']

overrides:
  - files: ['**/*.ts']
    rules:
      '@typescript-eslint/no-unsafe-member-access': off
      '@typescript-eslint/no-unsafe-return': off
