parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2022
  sourceType: module
  project: ['./tsconfig.json']

overrides:
  - files: ['**/*.ts']
    rules:
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-unsafe-assignment': off
      '@typescript-eslint/no-unsafe-call': off
      '@typescript-eslint/unbound-method': off
      '@typescript-eslint/no-unsafe-return': off
      '@typescript-eslint/restrict-template-expressions': off
      '@typescript-eslint/no-unsafe-member-access': off
      '@typescript-eslint/no-unsafe-argument': off
      '@typescript-eslint/no-unsafe-members': off
