extends:
  - '../../.eslintrc.yml'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'

plugins:
  - 'react'
  - 'react-hooks'

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2022
  sourceType: module
  project: ['./tsconfig.json', './tsconfig.tests.json']

rules:
  'react/react-in-jsx-scope': 'off'

settings:
  react:
    version: 'detect'
