version: '3.8'

services:
  db:
    image: postgres:16-alpine
    ports:
      - ${POSTGRES_PORT-5432}:5432
    env_file:
      - db.env
    volumes:
      - ./db.init.sh:/docker-entrypoint-initdb.d/db.init.sh:ro
