# We don’t want to only update the Angular version mentioned in the package.json file using dependabot, but also go through the ng update process.
# Angular CLI provides an automated tool to scan our code and automatically apply the code changes during the update from one version to the next version.

# Merge the ng-update PR first and the other dependabot Angular update PRs will be automatically closed.

name: "Update Angular Action"
on:
  schedule:
    - cron: '30 5 * * 1'

jobs:
  ng-update:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies
        uses: fast-facts/ng-update@v1
        with:
          base-branch: main
          repo-token: $
          project-path: ./packages/ui